### PR TITLE
signup and login implementation 

### LINKED ISSUE #6: login Backend implementation
We thought to first implement the login functionality by adding models, controllers and routes

### PR DESCRIPTION
**Pull request by kaxada**
# Description

this feature adds the sign up and login functionality to the app. 
- On signup, the user has to input the `name`, `email`, `password` and also `confirm password` fields. 
- the password will be hashed with *salting* before being stored in the database for security purposes.
- the server will then create a token that will last 10000 seconds. 
- on login, the user will sign in 2ith the `registered email` and the `registered password`.

This is a new feature and doesn't fix any issue

## Type of change
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update (*readme has been updated in the setup section*)

# How Has This Been Tested?
The following routes have been tested using postman
- [x] /users/signup
- [x] /users/login

# Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by EKaxada** [comment]
@jnsereko please review this PR for this feature. Just incase you've also made your branch, then push it up and reference it here so that we do the necessary changes

**Comment by jnsereko** [comment]
@EKaxada I was still testing my routes that's why i hadn't pushed but i am gonna merge, and pull changes.

**Review by jnsereko — APPROVED** [review]
looks good to me, Afterall am gonna have to change more stuff

**Comment by kaxada** [comment]
oooh now that this feature is done why don't you work on the storage of data feature which includes photos, documents and all other files that may be neccessary while  I work on the RTC and Instant Messaging? @jnsereko

**Pull request merged**
