### PR TITLE
Login Implimentation

### PR DESCRIPTION
**Pull request by jnsereko**
# Description

Added methods and models to support Login functionality.

Fixes # (https://github.com/Peacodove-Pty-Ltd/HomeSchoolAPI/issues/6)

## Login implementation

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by EKaxada** [comment]
@jnsereko I think you need to do a rebase for these branches. As you can see in my previous commits I have been able to successfully add all the necessary linting, deployments and the CI. So this branch is behind the main branch by a lot of commits. find a way of updating it and push a pull request.

**Comment by jnsereko** [comment]
@EKaxada u are right, this branch wasn't included by the time you added the liniting.  Am going to make it point to current

**Comment by EKaxada** [comment]
hahaha. You have deleted the branch. Alright just do a `git pull` in your project directory and you'll be good to go

**Comment by EKaxada** [comment]
@jnsereko it's now high time we minded about testing too.

**Comment by jnsereko** [comment]
> @jnsereko hahaha. You have deleted the branch. Alright just do a `git pull` in your project directory and you'll be good to go. Redo this feature and then make a PR. I'll be waiting tomorrow.

i have downloaded the branch and then deleted it.
am gonna fetch changes and then pull request again.  I guess that will do the magic

**Comment by jnsereko** [comment]
> @jnsereko it's now high time we minded about testing too.

I was learning about how to use PostMan to test the routes i created.
Do you think this will work for us?

**Pull request merged**
